services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U user -d studs" ]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build:
      context: ../backend
    environment:
      DB_USER: user
      DB_PASS: pass
      SPRING_PROFILES_ACTIVE: default
      ACTIVEMQ_URL: tcp://activemq:61616
      EXTERNAL_REST_URL: http://mock-external:80/post
    depends_on:
      pg:
        condition: service_healthy
      activemq:
        condition: service_started
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend

  activemq:
    image: apache/activemq-classic:5.18.3
    ports:
      - "61616:61616"
    healthcheck:
      test: [ "CMD-SHELL", "true" ]
      interval: 5s
      timeout: 3s
      retries: 20

  mock-external:
    image: kennethreitz/httpbin
    expose:
      - "80"
    healthcheck:
      test: [ "CMD-SHELL", "true" ]
      interval: 5s
      timeout: 3s
      retries: 10

  jmeter:
    image: justb4/jmeter:latest
    volumes:
      - ../backend/jmeter:/jmeter
      - ./jmeter-results:/results
    networks:
      - default
    command: -n -t /jmeter/LR2-musicband.jmx -l /results/results.jtl -e -o /results/report/ -Jbase_url=http://backend:8080
    depends_on:
      - backend
    profiles:
      - jmeter

volumes:
  pgdata:
